sudo: required
services:
	docker

before_install:
    - docker build taranadesai/complex_react_app_client_dev -f ./client/Dockerfile.dev

script:
    - docker run taranadesai/complex_react_app_client_dev npm test -- --cover
    
after_success:
    - docker build taranadesai/complex_react_app_client ./client
    - docker build taranadesai/complex_react_app_nginx ./nginx
    - docker build taranadesai/complex_react_app_server ./server    
    - docker build taranadesai/complex_react_app_worker ./worker
    # docker login
    # push those docker images to docker-hub
    
    
deploy:
    