version: '3'
services:
    postgres:
        image: 'postgres:latest'
    redis:
        image: 'redis:latest'
    nginx:
        restart: always
        build:
            dockerfile: Dockerfile.dev
            context: ./nginx
        ports:
            - '3050:80'
        depends_on:
            - api
            - client
    api:
        build:
            dockerfile: Dockerfile.dev
            context: ./server
        volumes:
            - /app/node_moduels
            - ./server:/app
        environment:
            - REDIS_HOST=redis
            - REDIS_PORT=6379 
            - PGUSER=postgres
            - PGPASSWORD=postgres_password
            - PGHOST=postgres
            - PGDATABASE=postgres
            - PGPORT=5432
        depends_on:
            - postgres
            - redis
    client:
        build:
            dockerfile: Dockerfile.dev
            context: ./client
        volumes:
            - /app/node_moduels
            - ./client:/app
    worker:
        build:
            dockerfile: Dockerfile.dev
            context: ./worker
        volumes:
            - /app/node_moduels
            - ./worker:/app
        environment:
            - REDIS_HOST=redis
            - REDIS_PORT=6379
        depends_on:
            - redis            